export const dummyProjects = [
  {
    id: "1",
    title: "TinyWallets",
    description: "Your budget tracking software reinvented.",
    date: "2026-01-24T09:15:00.000Z",
    totalVersions: 2,
  },
  {
    id: "2",
    title: "Welcomer",
    description: "A truly welcoming Discord bot.",
    date: "2026-01-28T14:42:00.000Z",
    totalVersions: 5,
  },
  {
    id: "3",
    title: "Patchwork",
    description: "Visual changelog builder for SaaS teams.",
    date: "2026-02-03T08:00:00.000Z",
    totalVersions: 8,
  },
  {
    id: "4",
    title: "Slotify",
    description: "Appointment scheduling without the friction.",
    date: "2026-02-07T11:30:00.000Z",
    totalVersions: 1,
  },
  {
    id: "5",
    title: "Inkdrop",
    description: "Markdown notes with offline-first sync.",
    date: "2026-02-10T16:20:00.000Z",
    totalVersions: 12,
  },
  {
    id: "6",
    title: "Stackwise",
    description: "Tech stack documentation for growing teams.",
    date: "2026-02-14T10:05:00.000Z",
    totalVersions: 3,
  },
  {
    id: "7",
    title: "Nudge",
    description: "Habit tracker built around micro-commitments.",
    date: "2026-02-18T07:45:00.000Z",
    totalVersions: 6,
  },
  {
    id: "8",
    title: "Vaultify",
    description: "Encrypted credential sharing for dev teams.",
    date: "2026-02-21T13:00:00.000Z",
    totalVersions: 4,
  },
];

export const dummyVersions = [
  {
    id: "1",
    title: "Initial analysis baseline",
    version: 1,
    date: "Jan 02, 2026",
    status: "completed" as const,
    issues: { minor: 3, major: 1, critical: 2, correct: 8 },
  },
  {
    id: "2",
    title: "Actor and flow alignment",
    version: 2,
    date: "Jan 06, 2026",
    status: "completed" as const,
    issues: { minor: 2, major: 2, critical: 1, correct: 10 },
  },
  {
    id: "3",
    title: "Data model first pass",
    version: 3,
    date: "Jan 09, 2026",
    status: "completed" as const,
    issues: { minor: 1, major: 3, critical: 0, correct: 12 },
  },
  {
    id: "4",
    title: "User stories cross-check",
    version: 4,
    date: "Jan 12, 2026",
    status: "completed" as const,
    issues: { minor: 4, major: 1, critical: 1, correct: 9 },
  },
  {
    id: "5",
    title: "Post-interview revision",
    version: 5,
    date: "Jan 15, 2026",
    status: "completed" as const,
    issues: { minor: 0, major: 2, critical: 0, correct: 15 },
  },
  {
    id: "6",
    title: "Stakeholder feedback integration",
    version: 6,
    date: "Jan 18, 2026",
    status: "failed" as const,
  },
  {
    id: "7",
    title: "Revised actor definitions",
    version: 7,
    date: "Jan 20, 2026",
    status: "completed" as const,
    issues: { minor: 1, major: 0, critical: 1, correct: 14 },
  },
  {
    id: "8",
    title: "Flow consistency rework",
    version: 8,
    date: "Jan 22, 2026",
    status: "in-progress" as const,
  },
  {
    id: "9",
    title: "Final pre-validation pass",
    version: 9,
    date: "Jan 23, 2026",
    status: "draft" as const,
  },
  {
    id: "10",
    title: "Production-ready baseline",
    version: 10,
    date: "Jan 24, 2026",
    status: "draft" as const,
  },
];

export const dummyIssues = [
  {
    id: "issue-001",
    title: "Missing User Story Coverage",
    description:
      'User Story "US-002: User can create profile" is not mapped to any BPMN activity.',
    severity: "critical",
    isResolved: false,
    xp: 25,
    confidenceScore: 95.75,
    content: `## Summary\nUser Story **"US-002: User can create profile"** is not mapped to any BPMN activity, creating a traceability gap.\n\n## Justification\nThe following activities were scanned and **none** match US-002:\n- \`Task_01\` — User Login\n- \`Task_02\` — Password Reset\n\n> A user story without a corresponding process activity cannot be validated or traced during audits.\n\n## Suggestions\n1. Add \`Task_04 — Create User Profile\` linked to US-002.\n2. Re-run the analysis after updating the BPMN diagram.`,
  },
  {
    id: "issue-002",
    title: "Unlinked Gateway Decision",
    description:
      "Gateway 'GW-03' has no outgoing sequence flows defined in the process model.",
    severity: "major",
    isResolved: false,
    xp: 15,
    confidenceScore: 88.4,
    content:
      "## Summary\nGateway **GW-03** has no outgoing sequence flows, causing a dead-end in the process.\n\n## Justification\nDuring static analysis, the following gateways were validated:\n- `GW-01` — Approved ✓\n- `GW-02` — Rejected ✓\n- `GW-03` — Pending **✗ no outgoing flows**\n\n## Suggestions\n1. Define at least two outgoing sequence flows for `GW-03`.\n2. Ensure each flow has a condition expression attached.",
  },
  {
    id: "issue-003",
    title: "Duplicate Task Label",
    description:
      'Two BPMN tasks share the identical label "Send Notification", causing ambiguity.',
    severity: "minor",
    isResolved: false,
    xp: 5,
    confidenceScore: 72.1,
    content:
      "## Summary\nTasks **Task_07** and **Task_12** both carry the label `Send Notification`, which introduces ambiguity in reporting and traceability.\n\n## Justification\nLabel uniqueness is required per BPMN 2.0 best practices. Duplicate labels affect:\n- Automated test mapping\n- Audit trail clarity\n\n## Suggestions\n1. Rename `Task_07` to `Send Email Notification`.\n2. Rename `Task_12` to `Send Push Notification`.",
  },
];
