import type { Metadata } from "next";

export const siteConfig = {
  name: "Corekt",
  productionUrl: "https://corekt.vercel.app",
  repositoryUrl: "https://github.com/MrInspection/corekt-frontend",
  seo: {
    title: "Corekt - Your AI powered coherence assistant",
    description: "Generated by generate next app",
    ogImageUrl: "/moussax-corekt.png",
    keywords: [] satisfies Metadata["keywords"],
    authors: [
      { name: "Moussax", url: "https://moussax.vercel.app" },
    ] satisfies Metadata["authors"],
  },
};

export type SiteConfig = typeof siteConfig;
